[connections.postgresql]
dialect = "postgresql"
host = "aws-1-ap-southeast-1.pooler.supabase.com"
port = 6543
database = "postgres"
username = "postgres.slbynqcaoydqtdreexag"
password = "z1SL9umcmylYYduN"
url = "postgresql://postgres.slbynqcaoydqtdreexag@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"
