[connections.postgresql]
dialect = "postgresql"
host = "db.slbynqcaoydqtdreexag.supabase.co" # SupabaseのSettingsにあるHost
port = 5432
database = "postgres"
username = "postgres"
password = "101ringo55carry"
